name: impact-poc

services:
  icpm:
    container_name: icpm-shiny
    image: ${ICPM_IMAGE}:${ICPM_VERSION}
    environment:
      NEO4J_URL: neo4j://graph-dataset:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASS: ${NEO4J_PASS}
    depends_on:
      - graph-dataset

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - icpm

  graph-dataset:
    image: ${GRAPH_IMAGE}:${GRAPH_VERSION}
    container_name: graph-dataset
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      CYPHER_USER: ${NEO4J_USER}
      CYPHER_PASS: ${NEO4J_PASS}
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 8G
      NEO4J_server_memory_pagecache_size: 4G
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASS}"
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - neo4j_logs:/logs
      - ${OUTPUT_DIR}:/app/datasets
    entrypoint: ["/bin/bash", "-c", "/init/init.sh"]
    deploy:
      resources:
        limits:
          memory: 12G # needs to be at least the sum of heap_max_size and pagecache_size
        reservations:
          memory: 8G

  dump-helper: # container with all the mounts ready to be used for dumping
    image: ${GRAPH_IMAGE}:${GRAPH_VERSION}
    container_name: dump-helper
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - neo4j_logs:/logs
      - ${OUTPUT_DIR}:/app/datasets
    entrypoint: ['sleep', 'infinity']


volumes:
  neo4j_data: { }
  neo4j_logs: { }
  neo4j_plugins: { }
